### PR TITLE
Added async functions to 4.0 compile target

### PR DESCRIPTION
**Pull request by Croug**

### CODE REVIEW

**Comment by Croug** [comment]
So aparently Task.Run wasn't defined until .net 4.5 so do you want me to add a new project with a 4.5 build target or change the 4.0 target to 4.5?

**Comment by Croug** [comment]
Also I'm still not entirely sure what UT is.

**Comment by gpailler** [comment]
I think it's better to add a new project targeting .Net 4.5 (some projects using MegaApiClient library target .Net 4.0). You can duplicate MegaApiClient-4.0 folder to do that.
About UT, I mean Unit Tests. You can add new UT in MegaApiClient.Tests project (or I can do it later if you prefer)

**Comment by Croug** [comment]
I'll go ahead and make that new compile target, as for the unit tests I'm not entirely sure what those are so it'd probably be better if you did them.

**Comment by gpailler** [comment]
Ok. I'll write new UTs

**Comment by Croug** [comment]
Alright added final commit, should work this time.

**Comment by Croug** [comment]
It appears the AppVeyor build failed but it doesn't appear to be from my changes, so you might want to look into that.

**Comment by theTwist84** [comment]
@Croug I downloaded you're develop branch what do I need to do for progress.

**Comment by Croug** [comment]
@theTwist84 Something like this:
Task task = mega.DownloadFileAsync(textFileNode, "C:\\TextFile.txt");
while(!task.IsCompleted) progressBar1.Value = mega.Progress;

**Comment by gpailler** [comment]
@Croug Tests are not really stable on AppVeyor and I have to rerun them sometimes. They are green now.

I think there is something to improve with your implementation. Now we have async methods but a single Progress property on MegaApiClient instance. I will try to improve that and allow to launch multiple operation async at same time (and get multiple progress)

**Comment by Croug** [comment]
@gpailler Yeah I'll keep thinking too, maybe a wrapper class for task that allows a progress property.

**Comment by Croug** [comment]
@theTwist84 just realized that I had left out a number on the download progress calculation, just added another commit to change that so you'll have to redownload.

**Comment by theTwist84** [comment]
Re-downloaded and it works flawlessly my program is a console application so I'm using https://gist.github.com/DanielSWolf/0ab6a96899cc5377bf54
for the progress bar and I modified it to use mega.Progress.
Thanks for the help.

**Comment by Croug** [comment]
@theTwist84 No problem, also is there any reason you're using for(;mega.Progres <= 100;) instead of while(mega.Progress <= 100)

**Comment by theTwist84** [comment]
No but I'm new C# and programming in general.

**Comment by Croug** [comment]
@theTwist84  Your code isn't reporting the mega progress, it's reporting the progress of random variable i. your code should look like this: https://gist.github.com/Croug/89e3dedea581bfc4bf07

**Comment by theTwist84** [comment]
It isn't using i https://github.com/theTwist84/HaloOnlineInstaller/blob/master/HaloOnlineInstaller/Program.cs#L41

**Pull request merged**
