### PR TITLE
#85 Add new Update and UpdateFile methods to update an existing file on Mega

### PR DESCRIPTION
**Pull request by gpailler**

### CODE REVIEW

**Comment by Sergio0694** [comment]
Hey @gpailler - any updates on this pull request?

**Comment by gpailler** [comment]
Hello @Sergio0694 
Sorry, I had no time to continue my work on this task. I will try to find some spare time next month to complete it

**Comment by Sergio0694** [comment]
Hey @gpailler, how's it going?
I saw you just pushed a new version out, so I assume you started working on this again?
Any ETA on this merge?

Thanks! 😄

**Comment by gpailler** [comment]
Yes, I pushed a hotfix for a blocker issue.
I still need to find time to finish this PR but I will try to find some hours, I swear ;-)

**Comment by Sergio0694** [comment]
Sure, no sweat! The workaround is working ok so far, thanks again for your effort! 😄

**Pull request closed without merging**
